### ISSUE TITLE
Glue crawler Athena table creation fails silently on invalid yml input

### ISSUE THREAD

**Issue by asparke2** [NREL/buildstockbatch#159]
**Describe the bug**
If the `aws > s3 >prefix` entry in the yml file has a trailing `/`, the s3 upload will work, and the glue crawler will be created, but no Athena table will be created because the s3 location will be invalid.

**To Reproduce**
1. Add a trailing `/` to the `aws:s3:prefix` entry in the yml file as shown below
```
postprocessing:
  aws:
    region_name: 'us-west-2'
    s3:
      bucket: eulp    
      prefix: simulation_output/regional_runs/comstock/region-1-fort-collins-3500-ts/
    athena:
      glue_service_role: service-role/AWSGlueServiceRole-default
      database_name: testing
      max_crawling_time: 300 #time to wait for the crawler to complete before aborting it
```
2. run a post-process only run

**Expected behavior**
First, sanitize the input to strip trailing `/`.  Second, check that files exist inside the target s3 bucket before initializing the glue crawler.

**Logs**
Root issue was identified by noticing `//` in the following line of `postprocessing.out`:

```
INFO:2020-05-22 15:00:22:buildstockbatch.postprocessing:Upload to S3 completed. The files are uploaded to: eulp/simulation_output/regional_runs/comstock/region-1-fort-collins-3500-ts//region-1-fort-collins-3500-ts/
```

**Platform (please complete the following information):**
- Eagle
- BuildStockBatch 0.18
- OpenStudio-BuildStock version, branch, or sha: comstockv1.8
- Local Desktop OS: Windows
