### ISSUE TITLE
Validate Kestrel user limits

### ISSUE THREAD

**Issue by afontani** [NREL/buildstockbatch#171]
## Problem

If a job is submitted with more than the required number of nodes or wall time, the job will stay in the queue forever. 

### Example:
The below block specified 60 workers for the post-processing, but in the Eagle documentation, the maximum nodes per user is 45 nodes.

```
eagle:
  n_jobs: 250
  minutes_per_sim: 45
  account: enduse
  sampling:
    time: 240
  postprocessing:
    time: 240
    n_workers: 60 # Too many big-mem nodes, limit is 44 + 1 for the head node.
```

## Potential Solution
Implement the constraints of the table on this webpage ([Eagle Job Partitions and Scheduling Policies](https://www.nrel.gov/hpc/eagle-job-partitions-scheduling.html)) into the validator so the submission errors out before being stuck in the queue.
