### ISSUE TITLE
Warn if duplicate upgrade names

### ISSUE THREAD

**Issue by asparke2** [NREL/buildstockbatch#190]
While doing QAQC on a recent ComStock run, I realized that there were multiple upgrades in the `yml` file that had the same name (see below).  Although I was able to differentiate them programmatically using the `upgrade_id`, making user-facing results plots required an extra mapping layer.   At a minimum I think it would be helpful to check and warn for this.  If there's no use case we can think of where you'd want to do this intentionally, perhaps it should even be a run-halting error?

```yml
upgrades:  
  - upgrade_name: Upgrade Roof Insulation
    options:
      - option: env_roof_insul_r_val|roof_insul_code
  - upgrade_name: Upgrade Roof Insulation
    options:
      - option: env_roof_insul_r_val|roof_insul_efficient
  - upgrade_name: Upgrade Wall Insulation
```
