### ISSUE TITLE
ResStock - Inverse Sample Weight

### ISSUE THREAD

**Issue by afontani** [NREL/buildstockbatch#234]
## Issue description

The sample weight is inverse to what we would expect. In a recent run with BuildStock Batch 0.20 I used the following YAML inputs:

```
baseline:
  n_buildings_represented: 133172057 # ACS 5-yr 2016
sampler:
  type: residential_quota
  args:
    n_datapoints: 550000
```

I would expect the weight to be `33,172,057/550,000 = 242.13`. However, the weight ended up being `0.00413 ~ 550,000/133,172,057`.

## Bug Location

I believe this is the issue in the ResStock `workflow_generator`.

https://github.com/NREL/buildstockbatch/blob/7f7e628d9e5fa24cf24016effe6732d863028eb1/buildstockbatch/workflow_generator/residential.py#L256
