### ISSUE TITLE
results folder not getting created when running precomputed sampler in AWS

### ISSUE THREAD

**Issue by phgupta** [NREL/buildstockbatch#346]
**Describe the bug**
When running the "precomputed" sampler on AWS, the "results" folder is not getting created in the S3 bucket. The S3 bucket contains  all the folders (i.e., assets.tar.gz, config.json, emr/, jobs.tar.gz, lambda_functions/ and weather/) except the "results" folder.  However, when the sampler is changed to "residential_quota_downselect", the results folder is getting created.

**To Reproduce**
1. This is the yaml file,
```
schema_version: '0.3'
buildstock_directory: ../resstock-2.5.0  # Relative to this file or absolute
project_directory: project_national  # Relative to buildstock_directory
output_directory: bsb_results
weather_files_url: https://data.nrel.gov/system/files/156/BuildStock_TMY3_FIPS.zip
# weather_files_path: /shared-projects/buildstock/weather/BuildStock_TMY3_FIPS.zip # Relative to this file or absolute path to zipped weather files

sampler:
  type: precomputed
  args:
    sample_file: buildstock.csv

workflow_generator:
  type: residential_default
  args:
    timeseries_csv_export:
      reporting_frequency: Hourly
      include_enduse_subcategories: true

baseline:
  n_buildings_represented: 133172057  # Total number of residential dwelling units in contiguous United States, including unoccupied units, resulting from a census tract level query of ACS 5-yr 2016 (i.e. 2012-2016), using this script: https://github.com/NREL/resstock-estimation/blob/master/sources/spatial/tsv_maker.py.

aws:
  # The job_identifier should be unique, start with alpha, not include dashes, and limited to 10 chars or data loss can occur
  job_identifier: eshu
  s3:
    bucket: xyz
    prefix: test/baseline5
  emr:
    worker_instance_count: 1
  region: us-west-2
  use_spot: false
  batch_array_size: 2
  # To receive email updates on job progress accept the request to receive emails that will be sent from Amazon
  notifications_email: abc@xyz.com

postprocessing:
  aws:
    region_name: 'us-west-2'
    s3:
      bucket: xyz
      prefix: test/baseline5
    athena:
      glue_service_role: service-role/AWSGlueServiceRole-default
      database_name: testing
      max_crawling_time: 300 #time to wait for the crawler to complete before aborting it

```

The buildstock.csv file is a small test file with 8 buildings in it. This was the file generated from the previous run with the "residential_quota_downselect " sampler.

**Expected behavior**
I expected the "results" folder to be generated along with the "timeseries" data (since "include_enduse_subcategories" is set to true)

**Logs**
This is the log file from AWS Batch (which includes a few log statements from my end too),
```
<html>
<body>
<!--StartFragment-->

2023-02-13T11:50:01.705-05:00 | _ __ _ __, _ __
-- | --
  | 2023-02-13T11:50:01.705-05:00 | ( / ) o // /( _/_ / ( / ) _/_ /
  | 2023-02-13T11:50:01.705-05:00 | /--< , ,, // __/ `. / __ _, /< /--< __, / _, /
  | 2023-02-13T11:50:01.705-05:00 | /___/(_/_(_(/_(_/_(___)(__(_)(__/ \|_/___/(_/(_(__(__/ /_
  | 2023-02-13T11:50:01.705-05:00 | Executing BuildStock projects with grace since 2018
  | 2023-02-13T11:50:01.705-05:00 | DEBUG:2023-02-13 11:50:01:__main__:region: us-west-2
  | 2023-02-13T11:50:01.893-05:00 | DEBUG:2023-02-13 11:50:01:__main__:Downloading assets
  | 2023-02-13T11:50:01.893-05:00 | DEBUG:2023-02-13 11:50:01:__main__:PG (aws.py): assests_file_path: /var/simdata/assets.tar.gz
  | 2023-02-13T11:50:10.563-05:00 | DEBUG:2023-02-13 11:50:10:__main__:Reading config
  | 2023-02-13T11:50:10.646-05:00 | DEBUG:2023-02-13 11:50:10:__main__:Getting job information
  | 2023-02-13T11:50:10.646-05:00 | DEBUG:2023-02-13 11:50:10:__main__:PG (aws.py): jobs_file_path: /var/simdata/jobs.tar.gz
  | 2023-02-13T11:50:10.699-05:00 | DEBUG:2023-02-13 11:50:10:__main__:Number of simulations = 2
  | 2023-02-13T11:50:10.700-05:00 | DEBUG:2023-02-13 11:50:10:__main__:Getting weather files
  | 2023-02-13T11:50:10.873-05:00 | DEBUG:2023-02-13 11:50:10:__main__:Downloading G2601630.epw.gz
  | 2023-02-13T11:50:10.989-05:00 | DEBUG:2023-02-13 11:50:10:__main__:Extracting G2601630.epw
  | 2023-02-13T11:50:11.003-05:00 | DEBUG:2023-02-13 11:50:11:__main__:Downloading G4800290.epw.gz
  | 2023-02-13T11:50:11.118-05:00 | DEBUG:2023-02-13 11:50:11:__main__:Extracting G4800290.epw
  | 2023-02-13T11:50:11.357-05:00 | DEBUG:2023-02-13 11:50:11:buildstockbatch.workflow_generator.residential:Generating OSW, sim_id=bldg0000003up00
  | 2023-02-13T11:50:11.358-05:00 | DEBUG:2023-02-13 11:50:11:__main__:Running bldg0000003up00
  | 2023-02-13T11:52:29.934-05:00 | DEBUG:2023-02-13 11:52:29:__main__:PG (aws.py): execute cls.cleanup_sim_dir
  | 2023-02-13T11:52:29.940-05:00 | DEBUG:2023-02-13 11:52:29:buildstockbatch.base:PG (base.py): cleanup_sim_dir: os.path.isfile(timeseries_filepath)
  | 2023-02-13T11:52:30.349-05:00 | DEBUG:2023-02-13 11:52:30:buildstockbatch.base:PG (base.py): cleanup_sim_dir: writing dataframe as parquet
  | 2023-02-13T11:52:30.555-05:00 | DEBUG:2023-02-13 11:52:30:__main__:PG (aws.py): done executing cls.cleanup_sim_dir
  | 2023-02-13T11:52:30.557-05:00 | INFO:2023-02-13 11:52:30:__main__:Archiving simulation outputs
  | 2023-02-13T11:52:32.744-05:00 | DEBUG:2023-02-13 11:52:32:__main__:Clearing out simulation directory
  | 2023-02-13T11:52:32.751-05:00 | DEBUG:2023-02-13 11:52:32:buildstockbatch.workflow_generator.residential:Generating OSW, sim_id=bldg0000004up00
  | 2023-02-13T11:52:32.752-05:00 | DEBUG:2023-02-13 11:52:32:__main__:Running bldg0000004up00
  | 2023-02-13T11:54:32.486-05:00 | DEBUG:2023-02-13 11:54:32:__main__:PG (aws.py): execute cls.cleanup_sim_dir
  | 2023-02-13T11:54:32.492-05:00 | DEBUG:2023-02-13 11:54:32:buildstockbatch.base:PG (base.py): cleanup_sim_dir: os.path.isfile(timeseries_filepath)
  | 2023-02-13T11:54:32.899-05:00 | DEBUG:2023-02-13 11:54:32:buildstockbatch.base:PG (base.py): cleanup_sim_dir: writing dataframe as parquet
  | 2023-02-13T11:54:33.133-05:00 | DEBUG:2023-02-13 11:54:33:__main__:PG (aws.py): done executing cls.cleanup_sim_dir
  | 2023-02-13T11:54:33.135-05:00 | INFO:2023-02-13 11:54:33:__main__:Archiving simulation outputs
  | 2023-02-13T11:54:35.102-05:00 | DEBUG:2023-02-13 11:54:35:__main__:Clearing out simulation directory
  | 2023-02-13T11:54:35.110-05:00 | DEBUG:2023-02-13 11:54:35:__main__:PG (aws.py): upload sim outputs tarfile to s3
  | 2023-02-13T11:54:35.301-05:00 | DEBUG:2023-02-13 11:54:35:__main__:PG (aws.py): done uploading sim outputs tarfile to s3

<!--EndFragment-->
</body>
</html>
```

The following log,
```
  | 2023-02-13T11:52:30.349-05:00 | DEBUG:2023-02-13 11:52:30:buildstockbatch.base:PG (base.py): cleanup_sim_dir: writing dataframe as parquet
```
logs right before the call to the following line of code in base.py
```
postprocessing.write_dataframe_as_parquet(
                tsdf,
                dest_fs,
                f'{simout_ts_dir}/up{upgrade_id:02d}/bldg{building_id:07d}.parquet'
            )
```
This function should have created the results folder and saved the parquet files in there.

However, the S3 bucket does not include the results folder. It looks like this,
![image](https://user-images.githubusercontent.com/15964401/218563429-ed8d2bbd-fc78-4fe9-8930-e975aee5e61d.png)

**Platform (please complete the following information):**
- Simulation platform: AWS
- BuildStockBatch version, branch, or sha: v0.21
- resstock or comstock repo version, branch, or sha: v2.5.0
- Local Desktop OS: Windows WSL2
